# Site settings
title: ANISH
email: "anishsarkar@proofschool.org"
description: "blog"
url: "https://anishsarkar.me"
baseurl: ""
share: false

# Owner/author information
owner:
  name:   Anish Sarkar
  avatar: img/self.jpg
  favicon: favicon.ico
  info: 

# Settings for comments helper
# Set 'provider' to the comment provider you want to use. (i.e.  Disqus, Intense Debate, livefyre, or Facebook Comments)
# Set 'provider' to false to turn commenting off globally.
#Set 'provider: false' to disable comments globally.
# Disable comments for individual pages/posts by specifying 'comments: false' in the page/post YAML Front Matter.
#
comments :
  provider : false
  disqus :
    short_name : ""

# Internal nav
nav:
  - HOME: "/"
  - GALLERY: "/gallery/"  
  - PROJECTS: "/projects/"
  - ABOUT: "/about/"

# All translation keys
translations:
 # 404.html
  permalink: "/404.md"

# Server
destination:      	 ./_site
port:             	 4000


# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
paginate_path: "/projects/page:num/"
permalink: "/projects/:title/"
categories_path: "/projects/category/"
tags_path: "/projects/tag/"
gems: 
 - jekyll-paginate
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# SiteMap
sitemap:
    file: "/sitemap.xml"
    exclude:
        - "/atom.xml"
        - "/feed.xml"
        - "/feed/index.xml"
    include_posts:
        - "/writing/"
    change_frequency_name: "change_frequency"
    priority_name: "priority"

collections:
  projects:
    output: true
    permalink: /:collection/:title/


defaults:
  - scope:
      path: ""
      type: "static_files"
    values:
      image: true